# This workflow will install node dependencies (and cache them), build the source code and run tests
name: Node.js CI

on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm install
      - run: npm run test
      - run: npm run build
