# This workflow will install node dependencies (and cache them), build the source code and run tests
name: Node.js CI

on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

      - run: npm install
      - run: npm run test
      - run: npm run build
