# This workflow will install node dependencies (and cache them), build the source code and run tests
name: Node.js CI

on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

      - run: npm install
      - run: npm run test
      - run: npm run build
